### ISSUE TITLE
Double Quick answer

### ISSUE THREAD

**Issue by Leoxur** [wasdennnoch/AndroidN-ify#1232] opened 2016-11-20 15:44 UTC
**Description**
In some app notification like Gmail, WhatsApp there are two answer button (One of the app and the other by n-ify) it's not a good and confortable view
**Module version (build version)**
783

**Comment by Robotit** [comment] 2016-12-12 20:52
Same on version 791, and true not comfortable to see plus it's confusing to see it duplicated.

**Comment by Maxr1998** [comment] 2016-12-12 22:53
Duplicate of #862, and invalid.

**Closed** 2016-12-12 22:53 UTC
Labels: duplicate, invalid
