### ISSUE TITLE
Missed up every thing on new builds.. qs , notifications 

### ISSUE THREAD

**Issue by amansingh63** [wasdennnoch/AndroidN-ify#905] opened 2016-09-20 12:58 UTC
After new build server is up .  The module is not working properly. Everything is messed up in qs and notifications usind motorola Moto g3 6.0.1 stock rom.

http://pastebin.com/QJExcygu
My xposed logs

. [
![screenshot_20160920-181914](https://cloud.githubusercontent.com/assets/8289918/18670907/9d3d3628-7f5f-11e6-8c73-289a663a6682.png)
](url)
![screenshot_20160920-181912](https://cloud.githubusercontent.com/assets/8289918/18670943/c0227e96-7f5f-11e6-9aed-9de8a551e9e9.png)
.

**Comment by ds84182** [comment] 2016-09-20 13:49
This is related to #835

**Comment by Silver-Fullbuster** [comment] 2016-09-20 17:15
Same problem. 
Xposed log:
http://pastebin.com/eivUc4cP
Logcat:
http://s000.tinyupload.com/index.php?file_id=02958557099332891127

**Comment by wasdennnoch** [comment] 2016-09-20 17:39
Can anydody provide a **deodexed** SystemUI?
`java.lang.NoSuchMethodError: com.android.systemui.statusbar.policy.MobileDataControllerImpl#setMobileDataEnabled(boolean)#exact`

**Comment by Silver-Fullbuster** [comment] 2016-09-20 17:43
I don't know how to deodex but here's my systemui apk and odex file:
Apk: https://drive.google.com/file/d/0B5D0pTHX0tlFVTRzZFBFSVRHNE0/view?usp=drivesdk
Odex: https://drive.google.com/file/d/0B5D0pTHX0tlFU09MVXZqNGNleTQ/view?usp=drivesdk

I did provide these in xda (I'm S¡lver there)

**Comment by wasdennnoch** [comment] 2016-09-20 17:45
Problem is that I can't deoxed it, during deodexing you need framework files (basically the whole /framework/ folder) of your device which means that you have to do it.

**Comment by Silver-Fullbuster** [comment] 2016-09-20 18:39
Thing is that I don't have a comp myself, at least not for my personal usage, and Google says I'll need a pc.. Is it possible for you to deodex if I upload all the required files?

**Comment by wasdennnoch** [comment] 2016-09-20 18:51
You can actually deodex using only your phone: http://forum.xda-developers.com/showthread.php?t=2541509

**Comment by amansingh63** [comment] 2016-09-20 19:30
https://drive.google.com/open?id=0BzDyS5Y6vDYVaFpCMXZocXVqQ0E


 Deodexed SystemUI Apk from Motorola Moto G 3 ..

**Comment by Silver-Fullbuster** [comment] 2016-09-20 19:30
Ain't working. Giving me errors.. ex:
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:40)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:686)
	at brut.androlib.Androlib.installFramework(Androlib.java:640)
	at brut.apktool.Main.cmdInstallFramework(Main.java:249)
	at brut.apktool.Main.main(Main.java:91)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:101)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 5 more

**Comment by wasdennnoch** [comment] 2016-09-20 21:06
Fixed with 429b3d1483e6862b10212a40d3a12f49d1666bb3

**Closed by wasdennnoch** 2016-09-20 21:06 UTC
Labels: crash
