### ISSUE TITLE
Lockscreen text & notif. drawer hiding

### ISSUE THREAD

**Issue by yzyboost** [wasdennnoch/AndroidN-ify#1230] opened 2016-11-18 15:12 UTC
**Description**
No lockscreen text & notification drawer after updating build 772 into build 774-783
**Module version (build version)**
Build 774 - 783
**Xposed log / logcat**
[xposed_error_20161118_193749.txt](https://github.com/wasdennnoch/AndroidN-ify/files/600220/xposed_error_20161118_193749.txt)

**Comment by yzyboost** [comment] 2016-11-18 15:13
![screenshot_20161118-194412](https://cloud.githubusercontent.com/assets/23522663/20434816/957d3d30-ade4-11e6-9364-9c4955b5d250.png)

**Comment by yzyboost** [comment] 2016-11-18 15:13
![screenshot_20161118-194421](https://cloud.githubusercontent.com/assets/23522663/20434828/a5c7a3e2-ade4-11e6-922c-24b31db721fe.png)

**Comment by bebolint98** [comment] 2016-11-19 11:59
Some problem here on cm13.

**Comment by yzyboost** [comment] 2016-11-19 13:56
Deactivate fix huge in experimental settings, fixed. But we need an update that will fixed the issue (not deactivating the fix huge under qs header).

**Comment by yzyboost** [comment] 2016-11-19 13:57
Using AICP Rom 6.0.1

**Comment by paphonbth** [comment] 2016-11-20 02:53
Duplicate of #1221

**Closed by paphonbth** 2016-11-20 02:53 UTC
