### ISSUE TITLE
PA and Anroid N-ify

### ISSUE THREAD

**Issue by lenzwagner** [wasdennnoch/AndroidN-ify#422] opened 2016-06-11 10:35 UTC
I think you already heared about it a lot and are already sick of it, but i wanna tell it again, but with help from my side. The log and my SystemUI.apk is attached.

The problem is that the QS Tiles are not shown and the Plus sign, PA introduced is hanging around in the wrong place. These issues are not nice looking, but i can live with it (of course it would be nice if you get it fixed) but the worst issue is, that the SystemUI.apk drains horrendously much battery.
I tried it with version 0.2.0 and of course with the latest experimental builds. Doesnt help. 
 If you need any further help, feel free to contact me. 

![screenshot_20160611-121703](https://cloud.githubusercontent.com/assets/10699985/15984557/35567d64-2fd0-11e6-972c-be8d0b2db938.png)

![screenshot_20160611-121653](https://cloud.githubusercontent.com/assets/10699985/15984566/d6943b6c-2fd0-11e6-85cd-44604862f583.png)

[SystemUi_and_Log.zip](https://github.com/wasdennnoch/AndroidN-ify/files/310196/SystemUi_and_Log.zip)

**Comment by wasdennnoch** [comment] 2016-06-11 16:01
I guess you already tried the option to hide the stock edit button. I had a look at the official PA source ( https://github.com/AOSPA/android_frameworks_base/blob/marshmallow/ ) and it should all work normally. Also your SystemUI is odexed, so it doesn't seem like you are running a custom ROM. Do I understand you right and PA is Paranoid Android?

**Comment by SlimShadys** [comment] 2016-06-11 17:43
^
The frameworks_base of PA is outdated on GitHub. Even if there is a marshmallow branch, the actual framework_base of PA Official build has been built locally, not pushed to Github yet :)

**Comment by wasdennnoch** [comment] 2016-06-11 17:45
If so, it will be hard to find the cause without any code to build on...

**Comment by SlimShadys** [comment] 2016-06-11 17:46
I've contacted them. They will push code soon. Will hit you up when they do it :)

**Comment by lenzwagner** [comment] 2016-06-24 09:11
@wasdennnoch The source codes have been pushed. https://github.com/AOSPA/android_frameworks_base
Hope this will help you

**Comment by wasdennnoch** [comment] 2016-07-05 19:24
Problems should be fixed with 99d10006aa99c7bd0748906a59f147a6faa938aa

**Closed** 2016-07-07 16:18 UTC
Labels: bug, keep in mind

**Comment by aviraxp** [comment] 2016-08-03 12:53
Sadly, this happens again on today‘s PA build. This time the 'don't disturb' icon becomes blank and 'plus' icon appears.

But have a nice vacation bro, I can bear with it.

**Comment by wasdennnoch** [comment] 2016-08-16 22:39
I again fixed many PA bugs, please test the latest build.
