### ISSUE TITLE
tiles opening even when they are not their

### ISSUE THREAD

**Issue by kanzariya99** [wasdennnoch/AndroidN-ify#668] opened 2016-08-05 13:44 UTC
---- 05-Aug-2016 2:46:20 PM ----

08-05 14:46:59.477  1650  1650 W XSharedPreferen: type=1400 audit(0.0:114828): avc: denied { search } for name="tk.wasdennnoch.androidn_ify" dev="mmcblk0p16" ino=8185 scontext=u:r:system_app:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0

08-05 14:46:59.487  1650  1650 W XSharedPreferen: type=1400 audit(0.0:114829): avc: denied { search } for name="tk.wasdennnoch.androidn_ify" dev="mmcblk0p16" ino=8185 scontext=u:r:system_app:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0

08-05 14:46:59.487  1628  1628 W re-initialized>: type=1400 audit(0.0:114830): avc: denied { search } for name="tk.wasdennnoch.androidn_ify" dev="mmcblk0p16" ino=8185 scontext=u:r:system_app:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0

08-05 14:46:59.487  1628  1628 W re-initialized>: type=1400 audit(0.0:114831): avc: denied { search } for name="tk.wasdennnoch.androidn_ify" dev="mmcblk0p16" ino=8185 scontext=u:r:system_app:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0

08-05 14:47:01.027  1683  1683 W XSharedPreferen: type=1400 audit(0.0:114832): avc: denied { search } for name="tk.wasdennnoch.androidn_ify" dev="mmcblk0p16" ino=8185 scontext=u:r:system_app:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0

08-05 14:47:01.027  1683  1683 W XSharedPreferen: type=1400 audit(0.0:114833): avc: denied { search } for name="tk.wasdennnoch.androidn_ify" dev="mmcblk0p16" ino=8185 scontext=u:r:system_app:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0

08-05 14:47:59.348  1087  1095 W CursorWrapperInner: Cursor finalized without prior close()

08-05 14:47:59.351  1087  1095 W CursorWrapperInner: Cursor finalized without prior close()

08-05 14:47:59.362  1087  1095 W CursorWrapperInner: Cursor finalized without prior close()

08-05 14:47:59.623   703  1597 I MaliEGL : [Mali]window_type=1, is_framebuffer=0, errnum = 0

08-05 14:47:59.624   703  1597 I MaliEGL : [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1

08-05 14:47:59.624   703  1597 I MaliEGL : [Mali]max_allowed_dequeued_buffers=3

08-05 14:47:59.763   450  2000 I art     : Note: end time exceeds epoch: 

08-05 14:48:01.569   450   746 I ActivityManager: START u0 {flg=0x14000000 cmp=com.whatsapp/.Conversation (has extras)} from uid 10098 on display 0

08-05 14:48:01.680   450  1167 W InputMethodManagerService: Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@4a30f68 (uid=10115 pid=1496)

08-05 14:48:01.688  1002  1002 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.

08-05 14:48:01.924   157   190 E BufferQueueProducer: [com.whatsapp/com.whatsapp.Conversation] allocateBuffers: slot 2 without buffer is not FREE

08-05 14:48:01.929  1002  1269 I MaliEGL : [Mali]window_type=1, is_framebuffer=0, errnum = 0

08-05 14:48:01.929  1002  1269 I MaliEGL : [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1

08-05 14:48:01.929  1002  1269 I MaliEGL : [Mali]max_allowed_dequeued_buffers=3

08-05 14:48:01.961   703  1597 I MaliEGL : [Mali]window_type=1, is_framebuffer=0, errnum = 0

08-05 14:48:01.961   703  1597 I MaliEGL : [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1

08-05 14:48:01.961   703  1597 I MaliEGL : [Mali]max_allowed_dequeued_buffers=3

08-05 14:48:02.133   450   486 I ActivityManager: Displayed com.whatsapp/.Conversation: +500ms

08-05 14:48:02.192   450   473 I memtrack_graphic: graphic_memtrack_get_memory match 4:      ion_mm_heap 1496  7864320  12 de6fa4c0 ddd9dc00

08-05 14:48:02.192   450   473 I memtrack_graphic:  : 1496 1496 7864320 12 655360

08-05 14:48:04.354  1002  1269 I MaliEGL : [Mali]window_type=1, is_framebuffer=0, errnum = 0

08-05 14:48:04.354  1002  1269 I MaliEGL : [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1

Logs are attached.

Procedure for reproduction
1:- pull down full notification panel
2:- click near user icon(nothing will happen)
3:- bring notification panel up once.
4:- again pull down it.
5:-click on user.
6:- then again click near user icon. It will trigger flashlight as I have flashlight tile over their in that area as u can see in screenshot I have attached.
EDIT:-
IT TRIGGERS ALL THE TILES.. 
example WHEN I CLICK ON TIME. IT ON/OFF WIFI 
All this happens once u click on user icon and then click any where on upper portion of notification panel.
very annoying bug.
I'm able to reproduce this bug with WiFi and flashlight tiles.

**Comment by bimmermeow** [comment] 2016-08-05 13:56
i'm on build 459 and can reproduce it. (lg g2 d802. cyanogenmod 13) unfortunately, i can't download newer builds since pabhonb's server doesn't work at the moment.

**Comment by kanzariya99** [comment] 2016-08-07 11:53
I can provide u newer built(not the newest)
Just give me ur mail id.

**Comment by kanzariya99** [comment] 2016-08-08 17:03
I'm still having this issue on built 507
I hope this will get a fix soon

**Comment by wasdennnoch** [comment] 2016-08-16 19:36
Fixed with 9db0b33fef87e2e354578543c5297c4b91103bd9

**Closed by wasdennnoch** 2016-08-16 19:36 UTC
