### ISSUE TITLE
Android Neko (easter egg) keeps crashing

### ISSUE THREAD

**Issue by byytelope** [wasdennnoch/AndroidN-ify#1227] opened 2016-11-18 12:56 UTC
When I press on the empty dish tile in QS and select a food, N-ify crashes and the weird thing is there's nothing in the Xposed logs. And I also found that if you lock the phone after pressing the empty dish, the pop-up shows up instead of the lockscreen. It goes away and the lockscreen shows up when I press any thing and crashes N-ify in the process.
I'm on near stock LP and module 783.

**Comment by byytelope** [comment] 2016-11-20 04:00
[xposed_error_20161120_085611.zip](https://github.com/wasdennnoch/AndroidN-ify/files/601856/xposed_error_20161120_085611.zip)

**Comment by wasdennnoch** [comment] 2016-11-20 09:54
As you said, the Xposed log doesn't help. We need a logcat.

**Comment by byytelope** [comment] 2016-11-20 10:40
Sorry about that. Here: [logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/601962/logcat.txt)

**Comment by paphonbth** [comment] 2016-11-20 14:34
Still no useful information in the log. Make sure the crash happens when you're capturing logs and please post full logs, not a trimmed one.

**Comment by byytelope** [comment] 2016-11-20 16:34
Pretty sure this one will have something useful. [logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/602159/logcat.txt)

**Comment by paphonbth** [comment] 2016-11-20 23:31
Found the cause. Will fix it as soon as I have access to my pc.

**Comment by byytelope** [comment] 2016-11-21 08:54
Ah, thank you.

**Comment by paphonbth** [comment] 2016-11-21 12:59
Should be fixed with 9fc189f.

**Comment by byytelope** [comment] 2016-11-21 18:26
Yeah that's fixed but found another bug. When I longpress on the Neko tile, it opens N-ify and crashes instantly. Here's the logcat: [logcat.txt](https://github.com/wasdennnoch/AndroidN-ify/files/604461/logcat.txt)

**Closed** 2017-05-26 12:11 UTC
Labels: LOG PLS
