### ISSUE TITLE
Instant replies (nougat style)

### ISSUE THREAD

**Issue by Sgmaster** [wasdennnoch/AndroidN-ify#1270] opened 2016-12-19 22:24 UTC
Hello. I have just configured the N-ify app (download from Play store and then update within the app).
After restart i can see two reply buttons on viber notifications (one opens the default viber reply window and the other is the instant reply from notification bar (nougat style). Isnt the old reply button supposed to dissapear?
Also on telegram notifications i only get the default reply button which opens the telegram reply window. I dont have instant reply at all, which is weird...
Please fix or assist me on the settings i have to change if that is the case, although i have tried almost any posssible setting on the app...
(I am using OP2 running stock 6.0.1)
Thank you

**Comment by Maxr1998** [comment] 2016-12-21 06:54
Duplicate of #862. About Telegram, it seems it doesn't support the API on MM, weirdly enough. Not fixable.

**Closed by Maxr1998** 2016-12-21 06:54 UTC
Labels: duplicate

**Comment by Sgmaster** [comment] 2016-12-21 18:18
About the telegram, I'm pretty sure it was working great when i had installed cm14 nougat...
Maybe you are missing something?
Eitherway, thank yoy for the reply
