### ISSUE TITLE
OOS 3.1.3 QS tiles disappear

### ISSUE THREAD

**Issue by karamanliev** [wasdennnoch/AndroidN-ify#1033] opened 2016-10-12 08:16 UTC
Is there a way to fix the QS tiles on the preview builds in OOS 3._._ ? I can provide everything you might need, just tell me. Here is a video of the bug - https://www.youtube.com/watch?v=zk0MPJv3oPQ. Here's a xposed log if it does any good - http://pastebin.com/BXyESrpa.

P.S.: Also there's a problem with the volume slider, it is not fullwidth, even with the option checked.

I'm using OPX on OOS 3.1.3, latest Xposed and latest N-ify build #697.

**Comment by sharans003** [comment] 2016-10-13 11:45
The same happens for Oxygen OS 3.1.0 (Running on oneplus 2. )

**Comment by sharans003** [comment] 2016-10-13 11:46
The same happens for Oxygen OS 3.1.0 (Running on oneplus 2.)

**Comment by Habylab** [comment] 2016-10-14 23:49
Same happens for me on 3.2.7, the latest OS. Nothing past #618 works for me.

**Comment by rafaelvcaetano** [comment] 2016-10-17 11:50
Same thing for Oxygen OS 2.2.3 (OnePlus X) using N-ify build 704.

**Comment by wasdennnoch** [comment] 2016-10-23 16:34
Does anybody know since which build this happens? Is it possible to re-add the tiles via the editor? (You have to change anything to actually update them, not just edit and done)

**Comment by rafaelvcaetano** [comment] 2016-10-23 16:44
Don't know in which build it started but when opening the edit screen, all tiles look normal, it's possible to activate/deactivate them and drag them around. When returning, the problem is still present. Items of the first row are correctly displayed.

**Comment by karamanliev** [comment] 2016-10-24 01:07
I can confirm that #618 is the last working version, after it I get bootloops or in the latest versions I get the QS tiles problem as described in the OP.

About your second question I think @rafaelvcaetano gave you the right answer, I tried your suggestions but it is still the same.

**Comment by Habylab** [comment] 2016-10-30 19:22
Yep, #618 is the last working version. I've been stuck on that for a fair while now. Crashes here and there anyway, as it's missing fixes.

**Comment by 5nickers** [comment] 2016-11-02 13:47
Are you still working on a fix? I think everyone with a OP3 or OP2 would be happy to test.

**Comment by paphonbth** [comment] 2016-11-02 14:57
No useful log provided yet.

**Comment by Habylab** [comment] 2016-11-02 19:44
How is the log not useful? It would be nice to know as there are logs posted above.

**Comment by Habylab** [comment] 2016-11-02 19:44
Also, as we know the exact build where it stops working, can you not revert that change in #619 and see if it works now?

**Comment by paphonbth** [comment] 2016-11-02 22:40
That log above has no error info. So it's useless.
Reverting that commit would break everything related to QS.
And please don't talk about build number here. It can cause confusions. For example,  the commit that triggered build 619 is 5655c99.

**Comment by wasdennnoch** [comment] 2016-11-05 21:37
Also a duplicate of #912

**Closed by wasdennnoch** 2016-11-05 21:37 UTC
Labels: bug
