### ISSUE TITLE
Battery tile doesn't expand completely from quick toggles

### ISSUE THREAD

**Issue by JaredTheWolf** [wasdennnoch/AndroidN-ify#747] opened 2016-08-30 19:44 UTC
https://gfycat.com/KaleidoscopicFinishedDalmatian

Device: Moto G3 osprey
ROM: Tesla by Ground Zero ROMs. AOSP 6.0.1
Xposed: latest as of this post

**Comment by wasdennnoch** [comment] 2016-08-30 19:49
Hey, I have the same background. And the same issue, we're working on it ;)

**Comment by wasdennnoch** [comment] 2016-09-04 11:15
Duplicate of #781.

**Closed by wasdennnoch** 2016-09-04 11:15 UTC
