### ISSUE TITLE
Google App Crash (Nullpointer) in '"Ok Google" detection' screen

### ISSUE THREAD

**Issue by AnonymFox** [wasdennnoch/AndroidN-ify#1047] opened 2016-10-13 16:40 UTC
The crashes with a Nullpointer exception provided below when navigating to voice -> "ok google" detection in the settings of the google app on the nexus 5 (latest official build, Buildnr: M4B30X) , Google App Version 6.6.14.21.arm, latest n-ify build from jenkins (nr: 697, oct 12, 2:54am), xposed v.86.
I verified that the issue only occures when n-ify is enabled within xposed.
This issue might be related to #1044 (google app might not be able to store/load configuration for voice detection anymore)

Nullpointer exception (logcat):
10-13 18:35:05.970  5851  5851 D AndroidRuntime: Shutting down VM
10-13 18:35:06.008  5851  5851 E AndroidRuntime: FATAL EXCEPTION: main
10-13 18:35:06.008  5851  5851 E AndroidRuntime: Process: com.google.android.googlequicksearchbox:search, PID: 5851
10-13 18:35:06.008  5851  5851 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.google.android.apps.gsa.speech.microdetection.adapter.a.auR()' on a null object reference
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at com.google.android.apps.gsa.staticplugins.aw.l.aGp(SourceFile:900)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at com.google.android.apps.gsa.staticplugins.aw.l$13.c(SourceFile:855)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at com.google.android.apps.gsa.staticplugins.aw.l$13.aB(SourceFile:841)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at com.google.android.apps.gsa.search.core.m.b$2.onPostExecute(SourceFile:1328)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at com.google.android.apps.gsa.shared.util.concurrent.c$2.run(SourceFile:158)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-13 18:35:06.008  5851  5851 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-13 18:35:06.010   913  1525 W ActivityManager:   Force finishing activity com.google.android.googlequicksearchbox/com.google.android.apps.gsa.velvet.ui.settings.SettingsActivity

**Comment by Maxr1998** [comment] 2016-10-14 18:34
Duplicate of #1046

**Closed** 2016-10-14 18:34 UTC
Labels: duplicate
