### ISSUE TITLE
QS header get messed and toogles don't show up on AICP 11

### ISSUE THREAD

**Issue by genesisalgor** [wasdennnoch/AndroidN-ify#560] opened 2016-07-14 17:45 UTC
Hi everything was working perfectly on build #361, but since #369 the header toogles get messed, and toogles don't show up in expanded view. Provided a log:

https://drive.google.com/file/d/0B_VqQAje0irIT2NiZF9RU2Y0OGM/view?usp=drivesdk

**Comment by genesisalgor** [comment] 2016-07-14 17:46
A Screenshot to show the issue:
https://drive.google.com/file/d/0B_VqQAje0irIOWwxaGhUQnlrU28/view?usp=drivesdk

**Comment by wasdennnoch** [comment] 2016-07-14 18:15
Please post your Xplosed log too.

**Comment by genesisalgor** [comment] 2016-07-14 18:24
https://drive.google.com/file/d/0B_VqQAje0irISVBZWHBvdXcyNVE/view?usp=drivesdk

Here go.

**Comment by wasdennnoch** [comment] 2016-07-14 19:39
Are you on the newest build? (418)

**Comment by genesisalgor** [comment] 2016-07-14 19:49
On build 419, and the bug occurs.

**Comment by wasdennnoch** [comment] 2016-07-14 19:51
I added some additional logging with the latest commits, please post your Xposed log again (sorry for all the logs ^^)

**Comment by genesisalgor** [comment] 2016-07-14 19:59
You can ask how many logs you want haha 

Here go:
https://drive.google.com/file/d/0B_VqQAje0irISFpGZVNmdzg5TGs/view?usp=drivesdk

**Comment by wasdennnoch** [comment] 2016-07-14 20:03
Sure that this is the whole log? It starts suddenly without the usual Xposed framework logging at the beginning ^^

**Comment by genesisalgor** [comment] 2016-07-14 20:06
Oh, my bad, I think I've cleared it. Taking it again, just after boot.

**Comment by genesisalgor** [comment] 2016-07-14 20:13
Here the new log, just after boot:
https://drive.google.com/file/d/0B_VqQAje0irISHJ6WDZEeUExbUE/view?usp=drivesdk

**Comment by wasdennnoch** [comment] 2016-07-14 20:19
There are no crashes; I'll have a deeper look tomorrow.

**Comment by genesisalgor** [comment] 2016-07-14 20:27
The weird is while the Qsicons get stuck, they get expanded too. So I have the shortcuts in the header stuck, and invisible expanded icons, editor. A video would be useful?

**Comment by wasdennnoch** [comment] 2016-07-14 20:30
Do you have the alternative QS loading method active? If so, disable to. If the issue persists, a video could be useful, yes.

**Comment by genesisalgor** [comment] 2016-07-14 20:51
The alternative method was disabled, enabled rebooted and tested no use, so I disabled it again. But checked that to get rid of this issue I have to disable the fancy animation... But I updated to MM to have the animation hehe

Here a video with the issue:
https://drive.google.com/file/d/0B_VqQAje0irIZ0lfR0FZOHNwMlE/view?usp=drivesdk

**Comment by wasdennnoch** [comment] 2016-07-14 21:04
That's very weird. You said you updated, does that mean the issue is gone?

**Comment by genesisalgor** [comment] 2016-07-14 21:08
Oh not, I meant that I updated to MM to get the animations working and have full experience of the module. Disabling animation make the issue stop, it seems to be related with the Rom AICP 11, as other guys also said about that issue. Everything was working perfectly until build #361, from #369 this issue started.

**Comment by wasdennnoch** [comment] 2016-07-14 21:19
Hm, try a different ROM? :p
ok no, I'll have a deeper look tomorrow xD

**Comment by genesisalgor** [comment] 2016-07-14 21:20
For me phone the other option is PA... So... Hehe xD
Take your time, thanks.

**Comment by wasdennnoch** [comment] 2016-07-16 14:19
I changed some things again, so... would you be so kind to post a new Xposed log with the lates build? :P

**Comment by genesisalgor** [comment] 2016-07-16 15:20
Here go a new Xposed Log:
https://drive.google.com/file/d/0B_VqQAje0irIYmhDdFdTT3FQeVU/view?usp=drivesdk

**Comment by wasdennnoch** [comment] 2016-07-19 12:15
Either you like to rearrange your tiles every second or the method gets called constantly for some reason, I'll add a check if something has changed to avoid unneccesary relayout.

**Comment by genesisalgor** [comment] 2016-07-19 14:24
:P
Well, when I was taking the log I tried to repeat the issue to certificate to have it on the log.

**Comment by genesisalgor** [comment] 2016-07-20 17:56
Need more log? Issue seems to have been a little aliviated, but still occurs, sometime when it get stuck again it kinda is forced to expand. The issue seems to have something with animations.

**Comment by wasdennnoch** [comment] 2016-07-20 18:24
Thanks, I don't need more, and from the logs I also can't really tell what exactly is worng because everything sems fine there.

**Comment by genesisalgor** [comment] 2016-07-21 02:51
That's sad hehe

**Comment by genesisalgor** [comment] 2016-07-21 17:56
BTW noticed that If I expand first the Qs N line of toogles, then wait for about 5 seconds and expand it the issue didn't occur, animation goes fine. If the issue occur, then reduce it again and waiting more and expanding it again make it work... ???

LOL

**Comment by genesisalgor** [comment] 2016-07-22 16:54
Addition:
If there is a animation going on notification as download progress bar, the bug occurs always while the progress bar is on it.

**Comment by genesisalgor** [comment] 2016-07-22 17:11
https://drive.google.com/file/d/0B_VqQAje0irINXB1SUNkcUtrT2M/view?usp=drivesdk

**Comment by wasdennnoch** [comment] 2016-07-22 18:19
Hold on, I  smell something, can you please test this version and send the log after playing around with the panel (don't edit the tiles please ^^): http://www.mediafire.com/download/hg82msta1s82gav/Android_N-ify_debug_setExpansionHook_err.apk

**Comment by genesisalgor** [comment] 2016-07-22 18:32
https://drive.google.com/file/d/0B_VqQAje0irIUnJkR09QaXZPMG8/view?usp=drivesdk

Here, I played a bit like on the video, see if it is useful. Also didn't edited just left it as was before.

**Comment by wasdennnoch** [comment] 2016-07-22 18:47
Hm, that wasn't it, there is absolutely nothing in the log now. Compiling another test version now...

**Comment by genesisalgor** [comment] 2016-07-22 18:48
I noticed that the log didn't contained anything rather than the normal.

**Comment by wasdennnoch** [comment] 2016-07-22 19:01
Next version; I basically added a log every time a method that leads to the animation aborts because of some conditions: http://www.mediafire.com/download/57y96isma16kb2x/Android_N-ify_debug_aicp_log.apk

**Comment by genesisalgor** [comment] 2016-07-22 19:09
https://drive.google.com/file/d/0B_VqQAje0irIcFdWSmJfZTlBZHM/view?usp=drivesdk

I think this time we hit the nail.

**Comment by wasdennnoch** [comment] 2016-07-22 19:22
Even weirder. The animators are not set up although in the previous log the setup method gets called.

**Comment by wasdennnoch** [comment] 2016-07-22 19:24
Changed some little things here, if that doesn't help I have to dive through the AICP source again: http://www.mediafire.com/download/bi7girf0qc9nki7/Android_N-ify_debug_aicp_log_2.apk

**Comment by wasdennnoch** [comment] 2016-07-22 19:25
Oh, please enable debug log with that ^^

**Comment by genesisalgor** [comment] 2016-07-22 19:31
https://drive.google.com/file/d/0B_VqQAje0irIbk9vOE5sZ1cxcTA/view?usp=drivesdk

Here, but I see the same "fancy animation not ready to start" message. 
I was with debug log enabled since beginning. :P

**Comment by wasdennnoch** [comment] 2016-07-22 19:33
Hm, there's no single debug message in the log :P
You should be able to enable it on the fly in the app

**Comment by genesisalgor** [comment] 2016-07-22 19:35
https://drive.google.com/file/d/0B_VqQAje0irIV3g0djduYnVKQW8/view?usp=drivesdk

But its enabled on the app. Lol

**Comment by wasdennnoch** [comment] 2016-07-22 19:38
Try to disable and enable it. Apart from that, new version because I noticed that onMeasure can get hooked multiple times but only unkooked once, that completely broke i for me when I once tried that: http://www.mediafire.com/download/jwn9je359c96adf/Android_N-ify_debug_aicp_log_3.apk

**Comment by genesisalgor** [comment] 2016-07-22 19:52
https://drive.google.com/file/d/0B_VqQAje0irIZ0N2Mm40Q24yX2s/view?usp=drivesdk

Here, I think its more the same :/

**Comment by wasdennnoch** [comment] 2016-07-22 19:58
I'll try my lock again tomorrow, it's late and very hot here, thanks for you patience :)

**Comment by genesisalgor** [comment] 2016-07-22 20:03
Thanks man, its a pleasure to help. hope things get sorted out.

**Comment by wasdennnoch** [comment] 2016-07-23 13:06
Now you can disable debug log, I just log the importnant things normally here: http://www.mediafire.com/download/pzr8zip06a2xiyg/Android_N-ify_debug_aicp_log_4.apk

**Comment by genesisalgor** [comment] 2016-07-23 15:09
https://drive.google.com/file/d/0B_VqQAje0irIeWh4Slg3TExMc3c/view?usp=drivesdk

Here

**Comment by wasdennnoch** [comment] 2016-07-23 18:51
Looks like as soon as the animators are set onMeasure gets hooked again which deletes the animators and creates an infinite circle. onMeasure only gets hooked when the tiles are set, so something in the animator setup seems to invalidate the tiles. Many thanks! We're onto something :D

**Comment by genesisalgor** [comment] 2016-07-23 20:15
Oh that's great, finally we got useful log haha /o/

**Comment by wasdennnoch** [comment] 2016-07-29 15:33
I pushed a commit that only resets the animators when the tiles changed, maybe that fixes that if the build succeeds.

**Comment by genesisalgor** [comment] 2016-07-30 15:24
Seems to have been fixed on #488 :DD

**Comment by wasdennnoch** [comment] 2016-07-30 15:37
Great! I guess I can close this then :)

**Closed by wasdennnoch** 2016-07-30 15:37 UTC
Labels: bug
