### ISSUE TITLE
Tiny album art bug in music player from builds 530+ 

### ISSUE THREAD

**Issue by pwrusr** [wasdennnoch/AndroidN-ify#1212] opened 2016-11-15 05:10 UTC
Can it be fixed with upcoming builds...!!!

**Comment by pwrusr** [comment] 2016-11-15 07:56
Probably notification hooks need an update (: @paphonb

**Comment by pwrusr** [comment] 2016-11-15 18:02
Suggested workaround @notification hooks.java (:

**Comment by pwrusr** [comment] 2016-11-15 18:02
Suggested workaround @notification hooks.java (:

**Comment by Freewander10** [comment] 2016-11-16 17:49
This seems to be a duplicate of #744

**Comment by pwrusr** [comment] 2016-11-16 20:27
then its my bad ...i hasnt noticed this issue ...it was tagged # can be reproduced !!!!!!!!!!!!!means it wil keep showing up ....waiting to close this issue on devs response (:

**Closed** 2016-11-16 23:39 UTC
