### ISSUE TITLE
QS tiles not showing in statusbar and twilight notification is not proper on One plus 2, 3.0 beta

### ISSUE THREAD

**Issue by vpeace** [wasdennnoch/AndroidN-ify#307] opened 2016-05-23 17:12 UTC
The pause button cannot be seen
![screenshot_20160523-223603](https://cloud.githubusercontent.com/assets/16059464/15478226/ddb6be04-2136-11e6-9a2d-07cb405197ed.png)
Also there is overlapping in the statusbar
![screenshot_20160523-223952](https://cloud.githubusercontent.com/assets/16059464/15478343/521b62f4-2137-11e6-9da0-f0e496e8146d.png)

**Comment by wasdennnoch** [comment] 2016-05-23 17:54
Please post your Xposed log

**Comment by vpeace** [comment] 2016-05-24 04:08
https://drive.google.com/file/d/0B2CdsR5872csaEpraEtWZWNhRGM/view?usp=drivesdk

**Comment by vpeace** [comment] 2016-05-24 14:59
That's what you asked for right?

**Comment by wasdennnoch** [comment] 2016-05-24 15:02
It is; Can you please test this version: https://ci.paphonb.xyz/job/AndroidN-ify/202/

**Comment by vpeace** [comment] 2016-05-24 16:55
No development still the same

**Comment by superhupeng** [comment] 2016-05-25 04:15
Oxgen os 3.0 beta2 has more problems. Qs is all not work.

**Comment by vpeace** [comment] 2016-05-26 06:28
https://drive.google.com/file/d/0B2CdsR5872csVlc3elo3R1NQZGs/view?usp=drivesdk
Xposed log on oos beta 2

**Comment by vpeace** [comment] 2016-05-26 16:34
Any help by the xposed log?Problem is it the same or different?

**Comment by wasdennnoch** [comment] 2016-05-26 16:47
The problem is that there are no errors in the log that could narrow down the problem. Or, in other words: The problem is that the setTiles method of the QSPanel gets called with an empty tiles list so that no tiles get added to the QuickQSPanel.

**Comment by wasdennnoch** [comment] 2016-05-26 17:55
Does this version change anything? https://ci.paphonb.xyz/job/AndroidN-ify/223/

**Comment by vpeace** [comment] 2016-05-27 05:04
There is something in the log which returns false I'm not very sure about what it is butt it is related to the quick settings

**Comment by vpeace** [comment] 2016-05-27 06:21
Yes build 223 has the Q's tiles show ...thanks for the hard work..only the Bluetooth tile doesn't work all the others working fine also there is no animation when I pull the statubar.. anyways thanks for getting it to work :)

**Comment by vpeace** [comment] 2016-05-27 06:28
The twilight notification problem still there though

**Comment by vpeace** [comment] 2016-05-27 10:35
The Bluetooth got solved ...thanks and sorry :)

**Comment by wasdennnoch** [comment] 2016-05-27 11:49
I just installed twilight and the notification is showing properly for me. Can you please post your log again after playing around with the notification? 

![screenshot_20160527-134448](https://cloud.githubusercontent.com/assets/10065021/15607183/3c2ee83a-2411-11e6-8eb0-07c997f99d81.png)

**Comment by vpeace** [comment] 2016-05-27 12:11
There should be a pause button which should show in the notification

**Comment by vpeace** [comment] 2016-05-27 12:19
Something like this

![screenshot_20160527-174810](https://cloud.githubusercontent.com/assets/16059464/15607820/416c5482-2433-11e6-8aad-0f7c869fd129.png)

**Comment by wasdennnoch** [comment] 2016-05-27 12:26
Ah, that makes sense. Well, the module _is_ working correctly. There are no icons in N, and the actions don't have any text that could be shown instead. Have to add a way to show the icons if there's no text.

**Comment by vpeace** [comment] 2016-05-27 13:22
Thanks what about the transition effect?

**Comment by vpeace** [comment] 2016-06-09 04:24
The emergency info does not show up on the lock screen...also the transition effect does not work.

**Comment by wasdennnoch** [comment] 2016-06-11 16:26
The emergency button is in the emergency dialer, and the transition is a known problem. I need a logcat for both crashes.

**Comment by wasdennnoch** [comment] 2016-06-11 16:46
Should be fixed with 53c967598041ace9d9a56c21d42f077fe2463a4b

**Closed** 2016-06-14 19:21 UTC
Labels: bug
