### ISSUE TITLE
Bug na barra de notificações

### ISSUE THREAD

**Issue by BrunoWeiman** [wasdennnoch/AndroidN-ify#1172] opened 2016-11-08 18:30 UTC
As opções de wifi entre outras da barra de notificações n são ativadas embora na barra de ferramentas estejam ativadas

**Comment by Maxr1998** [comment] 2016-11-08 19:30
Please only post issue reports in English!

**Comment by FreakyEnderman** [comment] 2016-11-09 16:22
Bug in the notification bar
I think he is saying that he enabled the wifi toggle or something but it didn't showed up in QS page

"The wifi option among other toggles are activated on the toolbar but they aren't activated on notifications bar"

Maybe I've failed translation. But still they need a log to solve the issue.

**Comment by wasdennnoch** [comment] 2016-11-10 15:04
That'd be a duplicate of #576

**Closed by wasdennnoch** 2016-11-10 15:04 UTC
Labels: LOG PLS, more info needed
