### ISSUE TITLE
NoSuchMethodError in Tuner on CandySix roms

### ISSUE THREAD

**Issue by Maxr1998** [wasdennnoch/AndroidN-ify#852] opened 2016-09-17 17:34 UTC
Method [addTunable()](https://github.com/CandyRoms/frameworks_base/blob/c6/packages/SystemUI/src/com/android/systemui/tuner/TunerService.java#L85) has different arguments.

Log & post on XDA: [#1](http://forum.xda-developers.com/showpost.php?p=68715220&postcount=9029), [#2](http://forum.xda-developers.com/showpost.php?p=68715220&postcount=9030)

`09-16 12:48:38.185 E/Xposed  (26539): java.lang.NoSuchMethodError: com.android.systemui.tuner.TunerService#addTunable(com.android.systemui.statusbar.phone.QSTileHost,java.lang.String)#bestmatch
09-16 12:48:38.185 E/Xposed  (26539): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:371)
09-16 12:48:38.185 E/Xposed  (26539): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:384)
09-16 12:48:38.185 E/Xposed  (26539): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1124)
09-16 12:48:38.185 E/Xposed  (26539): 	at tk.wasdennnoch.androidn_ify.systemui.qs.QSTileHostHooks$5.afterHookedMethod(QSTileHostHooks.java:253)
09-16 12:48:38.185 E/Xposed  (26539): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:743)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.phone.QSTileHost.<init>(<Xposed>)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:1227)
09-16 12:48:38.185 E/Xposed  (26539): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
09-16 12:48:38.185 E/Xposed  (26539): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:729)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(<Xposed>)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3411)
09-16 12:48:38.185 E/Xposed  (26539): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
09-16 12:48:38.185 E/Xposed  (26539): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:729)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(<Xposed>)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3407)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:706)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:916)
09-16 12:48:38.185 E/Xposed  (26539): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
09-16 12:48:38.185 E/Xposed  (26539): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:729)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(<Xposed>)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:230)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.ServiceMonitor.-wrap5(ServiceMonitor.java)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
09-16 12:48:38.185 E/Xposed  (26539): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-16 12:48:38.185 E/Xposed  (26539): 	at android.os.Looper.loop(Looper.java:148)
09-16 12:48:38.185 E/Xposed  (26539): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
09-16 12:48:38.185 E/Xposed  (26539): 	at java.lang.reflect.Method.invoke(Native Method)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-16 12:48:38.185 E/Xposed  (26539): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-16 12:48:38.185 E/Xposed  (26539): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)`

**Comment by wasdennnoch** [comment] 2016-09-18 17:18
The problem isn't the parameter type, it's because on Candy the QSTileHost is copied from L so it doesn't implement Tunable. Should hopefully be fixed with 05b84e2acb8f01420f8d7fd14121202b00e8f71b

**Closed by wasdennnoch** 2016-09-18 17:18 UTC

**Comment by Maxr1998** [comment] 2016-09-18 18:33
Ah, I see. Didn't know it was a global Lollipop bug. Thanks!
