### ISSUE TITLE
Ripples not clipped in non-expanded view

### ISSUE THREAD

**Issue by vemacs** [wasdennnoch/AndroidN-ify#517] opened 2016-07-06 17:04 UTC
Screenshots:

![](http://i.imgur.com/qdyjb7B.png)

![](http://i.imgur.com/Huq9UuJ.png)

Ideally, the ripples would be clipped to the QS background, but a good workaround would be to just clip them in the default pull-down state, and unclip during the animation (e.g. when the "No notifications" text disappears).

**Comment by wasdennnoch** [comment] 2016-07-06 17:57
^ Github logic. It's actually not a bug because that's how it behaves without clipping, but it shouldn't. Weird, I know.

**Comment by AniketDhoke** [comment] 2016-07-13 14:48
I think it is fixed in #410 build

**Closed** 2016-07-13 14:54 UTC
Labels: enhancement
