### ISSUE TITLE
Bugs with QS Tiles on build #504

### ISSUE THREAD

**Issue by juangcardoso** [wasdennnoch/AndroidN-ify#659] opened 2016-08-02 21:30 UTC
Hey, man! How are u?

Well... On build #504 I'm facing a strange behaviour, all related to QS Tiles.

- When I reboot my device the QS animation doesn't work;

- Then, I have to hit edit button to change tiles and fix the animation;

- When I do this, mobile data tile stop working and just work again when I reboot my device;

- Sometimes Battery Tile icon joins it's left tile icon and the two icon stay strange;

- All the tiles when I long press it redirects me to WIFI settings;

- I can't click on notification while QS are expanded;

- And now, when I writ this bug report, I get a new strange behaviour on qs tiles and it disappear when I start expanding it and  appears again when I finish expanding it.

See a video show the issues: https://youtu.be/6Ms0M-6GtaY

Xposed Log: https://drive.google.com/folderview?id=0B8oeUhpF28-2cGhlWno2cFVoNUk

Have a good night, man!

**Comment by juangcardoso** [comment] 2016-08-02 21:34
Another thing!

Sometimes I reboot the device and animation and mobile data tile fix the behaviour, but all the other bugs stays and the long press in tiles pass to redirect me to Bluetooth settings!

**Comment by wasdennnoch** [comment] 2016-08-02 21:47
You are on build 478 :confused:

**Comment by wasdennnoch** [comment] 2016-08-02 21:48
Maybe the updater is broken, download the newest version directly and uninstall this one before installing the new one.

**Comment by juangcardoso** [comment] 2016-08-02 21:51
No, I'm using build #504... I've downloaded it directly from Paphonb's Jenkins Server and catch the logs today. One at 17:24 and the other at 18:28 (Brazilian time). :/

**Comment by wasdennnoch** [comment] 2016-08-02 21:53
In the log it says version 478 and it's an error that already got fixed.

**Comment by juangcardoso** [comment] 2016-08-02 21:55
I'll catch new logs and upload again, wait a minute! :)

**Comment by juangcardoso** [comment] 2016-08-02 22:03
Well... A mistake of my part! Sorry!

I sent the wrong link! 😅

Here is the new one checked: https://drive.google.com/folderview?id=0B8oeUhpF28-2bWRocUNZNWFVSUk

**Comment by juangcardoso** [comment] 2016-08-02 22:09
And a screenshot just to be sure! XD

https://drive.google.com/file/d/0B8oeUhpF28-2SXNfMlg3QXBGWGM/view?usp=drivesdk

**Comment by wasdennnoch** [comment] 2016-08-02 22:39
That doesn't seem to be the whole log, at least it cuts with an eof.

**Comment by juangcardoso** [comment] 2016-08-02 22:45
Here is One more I catch exactly now: https://drive.google.com/file/d/0B8oeUhpF28-2OUxuX093SzBkSHM/view?usp=drivesdk

But this log is now in the situation I told you that sometimes, when I reboot the device it fix the animation and mobile data tile!

If you prefer I can try reboot to see if the errors appears and catch a new log.

**Comment by wasdennnoch** [comment] 2016-08-02 22:52
I'll have to change the animation setup anyways, the current implementation isn't reliable which sometimes causes what you described, no tiles until the end. 
I'm going on vacation tomorrow, so don't expect any fix in the next 10 days :p 
I'll contact you when I need more information.

**Comment by juangcardoso** [comment] 2016-08-02 22:54
No problema! You're a human too! XD

You deserve a rest too! :)

**Comment by wasdennnoch** [comment] 2016-08-24 13:38
Soooo does it work with the latest build? ^^

**Comment by juangcardoso** [comment] 2016-08-24 19:54
Well, I'm on build #531 and sometimes the QS Animation doesn't work after rebooting the device. It is strange because it doesn't happens all the times and every reboot. It seems a little bit random.

The edit button doesn't bugs the mobile data tile anymore.

When I long press the tiles they sends me to the correct configuration now. But just with Wifi, Mobile Data and Bluetooth. The other tiles doesn't have any effect while I long press it.

And I still can't clicking on a notification while QS are expanded.

And I think is a known issue but sometimes my notification have a white bar bellow the notification.

**Comment by juangcardoso** [comment] 2016-08-24 19:55
And sorry for taking a long time to awnser. I've forgotten GitHub! Haha

**Comment by juangcardoso** [comment] 2016-08-24 19:55
And... Again, you can ask how many files you need.

**Comment by wasdennnoch** [comment] 2016-08-29 18:17
- If the ROM doesn't have detail views for other tiles they won't be shown
- Disable the experimental feature to click on notifications when QS are expanded
- Heared of the white bar but can't reproduce it myself

At least the animation works sometimes, I'll tweak the code a bit so it waits longer until it sets up the animation.

**Comment by juangcardoso** [comment] 2016-08-29 18:26
I'll upload a vídeo showing you the White bar, the Animation and two issues with battery tile. Wait, man!

**Comment by juangcardoso** [comment] 2016-08-29 18:49
Well... I made the vídeo with build #550 but I've updated it antes there are the same issues i related in the video.

And another thing in video, the message about battery economy while has no margin on right side of the screen. Well, is all in the video.

Xposed log: https://drive.google.com/file/d/0B8oeUhpF28-2czlGQ2NrQy1EbEU/view?usp=drivesdk

Video:  https://youtu.be/HjAFzjHL77I

**Comment by juangcardoso** [comment] 2016-08-29 19:00
And another issue found here.

The function of add custom tiles doesn't work. I write the name to the tile and when I hit add it closes and do the animation of expanding tiles slowly without my command.

**Comment by wasdennnoch** [comment] 2016-08-29 19:12
I can reproduce the battery detail bugs, but not the disposition (but some others seem to have that issue too). In the custom tile menu you have to add the spec of the tile which is used internally, not the name which is displayed, we have to make that a bit more clear.

**Comment by juangcardoso** [comment] 2016-08-29 19:36
Well, I'll wait it. And sorry for disturbing u! ^^'

And another thing (disturbing u again ^^')...  I'd like to ask you to implement swipeable qs pages like in the pic. It is present on N Stock and I think it is already running with N-Ify in another Roms. 

https://drive.google.com/file/d/0B8oeUhpF28-2Y2lXSmdjWDJubnM/view?usp=drivesdk

**Comment by wasdennnoch** [comment] 2016-08-29 19:48
The pages are something I want to implement too (or paphonb, depending on who's quicker or less focused on fixing all kinds of bugs on weird ROMs :p (Probably me because he already has pages on CM)).

**Comment by juangcardoso** [comment] 2016-08-29 20:10
There is any system file I can provide to help you? If I can help, just ask! :D

**Comment by wasdennnoch** [comment] 2016-08-29 20:20
Not right now. And I also noticed that the custom tile option doesn't instantly work and has some issues (and you probably don't need a spec), but I'll have to look in the code to find out what actually happens. Just wait :P

**Comment by juangcardoso** [comment] 2016-08-29 20:35
Ok, thanks for the attention! :D

**Comment by paphonbth** [comment] 2016-08-30 00:11
Seems like the word "Add custom tile" may confuse people. It's just normal MM broadcast tile that can be added in systemui tuner. It can be used for apps like "Custom Quick Settings". I'll change the text to "Add broadcast tile" to don't confuse people.

**Comment by juangcardoso** [comment] 2016-08-30 00:56
Paphonb, I have added a tile here for NFC with Custom QS and I have no idea how. Haha

Trying to do that again...

**Comment by wasdennnoch** [comment] 2016-09-07 14:15
To summarize it, the only issues now is the misbehaving battery tile and the white heads-up bar?

**Comment by juangcardoso** [comment] 2016-09-07 14:34
Yes, and the wrong QS animation

**Comment by juangcardoso** [comment] 2016-09-07 18:00
Hey, MrWasdennnoch. I'm racing some issues now after build 202. The tiles are ALWAYS with the First line greater and I can't reorganize it because I can't reorganize it because I get SystemUI FC when I finish editing tiles. And more, ALL the tiles are repeated in the new tiles section.

https://drive.google.com/folderview?id=0B8oeUhpF28-2bWRocUNZNWFVSUk

And I think something get wrong with my device too because I can't take a logcat, it always shows "logcat read failure". Tried with ADB, with apps, and always the same error.

**Comment by juangcardoso** [comment] 2016-09-07 18:20
Update: Fixed the problem with logcat. And it is in the same folder of the link. Running build #604 and the issue persists.

**Comment by wasdennnoch** [comment] 2016-09-07 18:52
Fixed crash ^^

**Comment by juangcardoso** [comment] 2016-09-07 19:17
Working fine now and also the QS animation. Thanks! :D

Well. Going into another things.

When in landscape mode with QS expanded, the header becomes cut.

Also I'm having two issues related to battery tile.
When click on battery tile without expanding QS the percentage is cut.

In battery tile yet, when charging, the charging message has no margin at the right side.

https://drive.google.com/folderview?id=0B8oeUhpF28-2TVppMXAxdmR0UW8

You can see the screenshots and the Xposed log in the link.

**Comment by wasdennnoch** [comment] 2016-09-20 20:29
The "saver not available" warning indeed has no margin, it's like that on N too. The not fully expanded panel is known. I'll close this now as the main issues are fixed ;)

**Closed by wasdennnoch** 2016-09-20 20:29 UTC
Labels: bug
